import { Model } from "@/types";

export const MODEL_LIST: Model[] = [
  {
    name: "sample-model_01",
    base_model: "개선 모델",
    status: "done",
    tags: ["마취과", "내과"],
    created_at: "2024-03-23",
    description: "말 파행진단에 관한 모델입니다.",
  },
  {
    name: "sample-model_02",
    base_model: "개선 모델",
    status: "progress",
    tags: ["마취과", "내과"],
    created_at: "2024-03-23",
    description: "말 파행진단에 관한 모델입니다.",
  },
  {
    name: "sample-model_03",
    base_model: "개선 모델",
    status: "failed",
    tags: ["마취과", "내과"],
    created_at: "2024-03-23",
    description: "말 파행진단에 관한 모델입니다.",
  },
  {
    name: "sample-model_01",
    base_model: "개선 모델",
    status: "done",
    tags: ["마취과", "내과"],
    created_at: "2024-03-23",
    description: "말 파행진단에 관한 모델입니다.",
  },
  {
    name: "sample-model_02",
    base_model: "개선 모델",
    status: "progress",
    tags: ["마취과", "내과"],
    created_at: "2024-03-23",
    description: "말 파행진단에 관한 모델입니다.",
  },
  {
    name: "sample-model_03",
    base_model: "개선 모델",
    status: "failed",
    tags: ["마취과", "내과"],
    created_at: "2024-03-23",
    description: "말 파행진단에 관한 모델입니다.",
  },
  {
    name: "sample-model_01",
    base_model: "개선 모델",
    status: "done",
    tags: ["마취과", "내과"],
    created_at: "2024-03-23",
    description: "말 파행진단에 관한 모델입니다.",
  },
  {
    name: "sample-model_02",
    base_model: "개선 모델",
    status: "progress",
    tags: ["마취과", "내과"],
    created_at: "2024-03-23",
    description: "말 파행진단에 관한 모델입니다.",
  },
  {
    name: "sample-model_03",
    base_model: "개선 모델",
    status: "failed",
    tags: ["마취과", "내과"],
    created_at: "2024-03-23",
    description: "말 파행진단에 관한 모델입니다.",
  },
];
